version: "3"
services:
  api:
    container_name: wildfire-api
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    ports:
      - "8081:8000"
      - "4011:3011"
    command: >
      sh -c "python manage.py migrate && python manage.py runserver_plus 0.0.0.0:8000 --cert-file cert.crt --key-file cert.key"
    volumes:
      - ./api:/api
      - ./polygons:/polygons
      - ./svc:/svc
    env_file:
      - .env
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
  ui:
    container_name: wildfire-ui
    build:
      context: .
      dockerfile: ui.Dockerfile
    user: root
    ports:
      - "3000:3000"
    command: >
      npm start
    volumes:
      - ./ui:/ui
    env_file:
      - .env
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: wildfire-db
    image: postgis/postgis:15-3.3
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
    ports:
      - "6662:5432"
    volumes:
      - ./db:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1s
      timeout: 5s
      retries: 20
      start_period: 30s
  celery:
    container_name: wildfire-celery
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    command: >
      sh -c "celery -A wildfire_assessment worker --loglevel=info"
    env_file:
      - .env
    volumes:
      - ./api:/api
      - ./svc:/svc
      - ./polygons:/polygons
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
      api:
        condition: service_started
  celery-beat:
    container_name: wildfire-celery-beat
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    env_file:
      - .env
    command: >
      sh -c "celery -A wildfire_assessment beat --loglevel=info"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
  redis:
    container_name: wildfire-redis
    image: "redis:alpine"
    ports:
      - "6380:6379"
    restart: on-failure
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
