"""
Django settings for the Wildfire Assessment API.

Generated by 'django-admin startproject' using Django 4.2.


For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import logging
import os
from pathlib import Path

from celery.schedules import crontab
from django.core.exceptions import ImproperlyConfigured

# Auto-configure OpenTelemetry if the SDK is installed and not disabled.
# This ensures instrumentation works even when the process is forked
# (e.g. runserver_plus auto-reloader, debugpy).
if os.environ.get("OTEL_SDK_DISABLED") != "true":
    try:
        from opentelemetry import trace

        if type(trace.get_tracer_provider()).__name__ == "ProxyTracerProvider":
            from opentelemetry.instrumentation.auto_instrumentation import initialize

            initialize()
    except ImportError:
        pass

logging.basicConfig(level=logging.INFO)

LOG = logging.getLogger(__name__)


def _env(name, default=None):
    """Read an optional environment variable."""
    return os.environ.get(name, default)


def _env_bool(name, default=False):
    """Read an environment variable as a boolean."""
    raw = os.environ.get(name)
    if raw is None:
        return default
    return raw.strip().lower() in ("1", "true", "yes", "on")


def _env_list(name, default=""):
    """Read a comma-separated environment variable as a list."""
    raw = os.environ.get(name, default)
    return [item.strip() for item in raw.split(",") if item.strip()]


def _env_required(name):
    """Read a required environment variable, raising a clear error when unset."""
    value = os.environ.get(name)
    if not value:
        raise ImproperlyConfigured(
            f"Environment variable {name} is required but not set. "
            "See .env.example for the expected configuration."
        )
    return value


# Check the environment
ENV = os.environ.get("ENV", "local")

# Core settings
SECRET_KEY = _env_required("DJANGO_SECRET_KEY")
DEBUG = _env_bool("DJANGO_DEBUG", False)
ALLOWED_HOSTS = _env_list("DJANGO_ALLOWED_HOSTS", "localhost")
CSRF_TRUSTED_ORIGINS = _env_list("DJANGO_CSRF_TRUSTED_ORIGINS", "")

# Database
DB_NAME = _env_required("DB_NAME")
DB_USERNAME = _env_required("DB_USERNAME")
DB_PASSWORD = _env_required("DB_PASSWORD")
DB_HOST = _env_required("DB_HOST")

# Auth0 (kept until the native authentication migration replaces it)
SOCIAL_AUTH_AUTH0_DOMAIN = _env("SOCIAL_AUTH_AUTH0_DOMAIN", "your-domain.auth0.com")
SOCIAL_AUTH_AUTH0_KEY = _env("SOCIAL_AUTH_AUTH0_KEY", "your-client-id")
SOCIAL_AUTH_AUTH0_SECRET = _env("SOCIAL_AUTH_AUTH0_SECRET", "your-client-secret")
SOCIAL_AUTH_AUTH0_SCOPE = _env_list("SOCIAL_AUTH_AUTH0_SCOPE", "openid,email,profile")
SOCIAL_AUTH_TRAILING_SLASH = _env_bool("SOCIAL_AUTH_TRAILING_SLASH", True)

AUTH0_AUDIENCE = _env("AUTH0_API_AUDIENCE", "")
AUTH0_DOMAIN = SOCIAL_AUTH_AUTH0_DOMAIN
AUTH0_ISSUER = f"https://{AUTH0_DOMAIN}/"
AUTH0_JWKS_URL = f"{AUTH0_ISSUER}.well-known/jwks.json"
AUTH0_EMAIL_CLAIM = _env("AUTH0_EMAIL_CLAIM", "email")
AUTH0_HTTP_TIMEOUT = float(_env("AUTH0_HTTP_TIMEOUT", "5"))
AUTH0_MANAGEMENT_CLIENT_ID = _env("AUTH0_MANAGEMENT_CLIENT_ID", "")
AUTH0_MANAGEMENT_CLIENT_SECRET = _env("AUTH0_MANAGEMENT_CLIENT_SECRET", "")
AUTH0_MANAGEMENT_AUDIENCE = f"https://{AUTH0_DOMAIN}/api/v2/"
AUTH0_MANAGEMENT_TOKEN_URL = f"https://{AUTH0_DOMAIN}/oauth/token"

# Storage (Google Cloud Storage)
GCS_BUCKET_NAME = _env("GCS_BUCKET_NAME", "wildfire-analyser-outputs")
GCS_APP_BUCKET_NAME = _env("GCS_APP_BUCKET_NAME", "wildfire-assessment-assets")
GCS_APP_PREFIX = _env("GCS_APP_PREFIX", "dev")

# AI providers (optional; the app starts without them)
GEMINI_API_KEY = _env("GEMINI_API_KEY")
OPENAI_API_KEY = _env("OPENAI_API_KEY")

# Observability (Grafana Cloud, removed in the V1 cleanup phase)
GRAFANA_CLOUD_OTLP_ENDPOINT = _env("GRAFANA_CLOUD_OTLP_ENDPOINT", "")
GRAFANA_CLOUD_INSTANCE_ID = _env("GRAFANA_CLOUD_INSTANCE_ID", "")
GRAFANA_CLOUD_API_KEY = _env("GRAFANA_CLOUD_API_KEY", "")

# Email (console backend by default; SMTP on the VPS)
EMAIL_BACKEND = _env("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = _env("EMAIL_HOST", "")
EMAIL_PORT = int(_env("EMAIL_PORT", "587"))
EMAIL_HOST_USER = _env("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = _env("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = _env_bool("EMAIL_USE_TLS", True)
EMAIL_USE_SSL = _env_bool("EMAIL_USE_SSL", False)
DEFAULT_FROM_EMAIL = _env("DEFAULT_FROM_EMAIL", "noreply@localhost")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

STATIC_URL = "static/"

STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATICFILES_STORAGE = "whitenoise.storage.StaticFilesStorage"

STATICFILES_DIRS = [
    BASE_DIR / "api" / "static",
]

REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "wildfire_assessment.authentication.Auth0JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "EXCEPTION_HANDLER": "wildfire_assessment.exception_handler.custom_exception_handler",
}


# Application definition

INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    "social_django",
    "rest_framework",
    "django_extensions",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "wildfire_assessment",
]

MIDDLEWARE = [
    "wildfire_assessment.middleware.MalformedURLMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "api.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "api", "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "social_django.context_processors.backends",
            ],
        },
    },
]

WSGI_APPLICATION = "api.wsgi.application"

if not AUTH0_AUDIENCE:
    LOG.warning(
        "AUTH0_API_AUDIENCE is not configured. API requests that require Auth0 tokens will fail."
    )

# PostgreSQL
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": DB_NAME,
        "USER": DB_USERNAME,
        "PASSWORD": DB_PASSWORD,
        "HOST": DB_HOST,
        "PORT": "5432",
        "CONN_MAX_AGE": 600,
    }
}


LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/admin/"

AUTHENTICATION_BACKENDS = {
    "social_core.backends.auth0.Auth0OAuth2",
    "django.contrib.auth.backends.ModelBackend",
}

SOCIAL_AUTH_PIPELINE = (
    "social_core.pipeline.social_auth.social_details",
    "social_core.pipeline.social_auth.social_uid",
    "wildfire_assessment.social_pipeline.social_user",
    "social_core.pipeline.user.get_username",
    "social_core.pipeline.social_auth.associate_by_email",
    "social_core.pipeline.user.create_user",
    "social_core.pipeline.social_auth.associate_user",
    "social_core.pipeline.social_auth.load_extra_data",
    "social_core.pipeline.user.user_details",
)
# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Redis cache — use db 1 so it does not collide with Celery (db 0).
# Needed for multi-worker deployments (gunicorn on ECS) where LocMemCache
# is per-process and AI conversation cache becomes invisible across workers.
_REDIS_URL = os.environ.get("CELERY_BROKER_URL", "redis://redis:6379/0")
_REDIS_CACHE_URL = _REDIS_URL.rsplit("/", 1)[0] + "/1"

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": _REDIS_CACHE_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}

# Celery configuration — Redis runs in the docker-compose service named "redis"
CELERY_BROKER_URL = _REDIS_URL
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", CELERY_BROKER_URL)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_IMPORTS = (
    "wildfire_assessment.svc.processor",
    "wildfire_assessment.svc.notification",
)
CELERY_BEAT_SCHEDULE = {
    "cleanup-old-read-notifications": {
        "task": "wildfire_assessment.svc.notification.cleanup_old_read_notifications",
        "schedule": crontab(hour=9, minute=0),  # 09:00 UTC = 06:00 BRT
    },
    "cleanup-stale-deliverables": {
        "task": "wildfire_assessment.svc.processor.cleanup_stale_deliverables",
        "schedule": crontab(minute="*/30"),
    },
}

# Terms of Service — bump this date to force all users to re-accept.
TERMS_LAST_UPDATED = "2026-02-25"

# django-unfold admin theme
UNFOLD = {
    "SITE_TITLE": "Wildfire Assessment",
    "SITE_HEADER": "Wildfire Assessment Admin",
    "SITE_SYMBOL": "local_fire_department",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "Authentication",
                "separator": True,
                "items": [
                    {
                        "title": "Users",
                        "icon": "people",
                        "link": "/admin/auth/user/",
                    },
                ],
            },
            {
                "title": "Wildfire Assessment",
                "separator": True,
                "items": [
                    {
                        "title": "Countries",
                        "icon": "public",
                        "link": "/admin/wildfire_assessment/country/",
                    },
                    {
                        "title": "Areas of Interest",
                        "icon": "map",
                        "link": "/admin/wildfire_assessment/areaofinterest/",
                    },
                    {
                        "title": "Analysis Runs",
                        "icon": "satellite_alt",
                        "link": "/admin/wildfire_assessment/analysisrun/",
                    },
                    {
                        "title": "Notifications",
                        "icon": "notifications",
                        "link": "/admin/wildfire_assessment/notification/",
                    },
                    {
                        "title": "AI Provider",
                        "icon": "smart_toy",
                        "link": "/admin/wildfire_assessment/aiprovider/",
                    },
                ],
            },
            {
                "title": "Reports",
                "separator": True,
                "items": [
                    {
                        "title": "Analytics Dashboard",
                        "icon": "analytics",
                        "link": "/admin/analytics/",
                    },
                    {
                        "title": "User Activity",
                        "icon": "person_search",
                        "link": "/admin/user-activity/",
                    },
                ],
            },
        ],
    },
}


if ENV in ["local", "dev"]:
    REST_FRAMEWORK["DEFAULT_SCHEMA_CLASS"] = "drf_spectacular.openapi.AutoSchema"
    INSTALLED_APPS += ["drf_spectacular"]

    SPECTACULAR_SETTINGS = {
        "TITLE": "Wildfire Assessment API V2",
        "DESCRIPTION": "Auto generated openApi 3.0 docs",
        "VERSION": "1.0.0",
        "SORT_OPERATION_PARAMETERS": False,
        "APPEND_COMPONENTS": {
            "securitySchemes": {
                "BearerAuth": {
                    "type": "http",
                    "scheme": "bearer",
                    "bearerFormat": "JWT",
                    "description": "JWT Authorization header using the Bearer scheme. Example: 'Authorization: Bearer <token>'",
                }
            }
        },
        "SECURITY": [{"BearerAuth": []}],
    }

    # DJANGO CORS HEADERS
    INSTALLED_APPS += ["corsheaders"]

    MIDDLEWARE.insert(2, "corsheaders.middleware.CorsMiddleware")
    CORS_ALLOW_CREDENTIALS = True
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOW_METHODS = [
        "DELETE",
        "GET",
        "OPTIONS",
        "PATCH",
        "POST",
        "PUT",
    ]

    CORS_ALLOW_HEADERS = [
        "accept",
        "accept-encoding",
        "authorization",
        "content-type",
        "dnt",
        "origin",
        "user-agent",
        "x-csrftoken",
        "x-requested-with",
    ]

    CORS_EXPOSE_HEADERS = [
        "x-ai-provider",
    ]

    os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true"  # only use in development
