"""
Django settings for the api project.

Generated by 'django-admin startproject' using Django 4.2.


For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import json
import logging
import os
from pathlib import Path

from celery.schedules import crontab

# Auto-configure OpenTelemetry if the SDK is installed and not disabled.
# This ensures instrumentation works even when the process is forked
# (e.g. runserver_plus auto-reloader, debugpy).
if os.environ.get("OTEL_SDK_DISABLED") != "true":
    try:
        from opentelemetry import trace

        if type(trace.get_tracer_provider()).__name__ == "ProxyTracerProvider":
            from opentelemetry.instrumentation.auto_instrumentation import initialize

            initialize()
    except ImportError:
        pass

from wildfire_assessment.svc.aws import get_aws_secret_manager_secret

logging.basicConfig(level=logging.INFO)
logging.getLogger("botocore").setLevel(logging.WARNING)

LOG = logging.getLogger(__name__)

# Check the environment
ENV = os.environ.get("ENV", "local")
USE_LOCAL_SECRET = os.environ.get("SKIP_AWS_SECRETS") == "1"


if USE_LOCAL_SECRET:
    secret = {
        "SOCIAL_AUTH_AUTH0_DOMAIN": "your-domain.auth0.com",
        "SOCIAL_AUTH_AUTH0_KEY": "your-client-id",
        "SOCIAL_AUTH_AUTH0_SECRET": "your-client-secret",
        "SOCIAL_AUTH_AUTH0_SCOPE": "openid,email,profile",
        "S3_BUCKET_NAME": "your-s3-bucket-name",
        "DJANGO_ALLOWED_HOSTS": "localhost",
        "DJANGO_SECRET_KEY": "your-secret-key",
        "DJANGO_DEBUG": "True",
        "DJANGO_CSRF_TRUSTED_ORIGINS": "http://localhost",
        "DB_USERNAME": "postgres",
        "DB_PASSWORD": "supersecretpassword",
        "DB_NAME": "app",
        "DB_HOST": "db",
        "AUTH0_API_AUDIENCE": "your-auth0-api-audience",
        "AUTH0_EMAIL_CLAIM": "email",
        "AUTH0_HTTP_TIMEOUT": "5",
        "AUTH0_MANAGEMENT_CLIENT_ID": "your-auth0-management-client-id",
        "AUTH0_MANAGEMENT_CLIENT_SECRET": "your-auth0-management-client-secret",
        "AUTH0_MANAGEMENT_AUDIENCE": "https://your-domain.auth0.com/api/v2/",
        "AUTH0_MANAGEMENT_TOKEN_URL": "https://your-domain.auth0.com/oauth/token",
        "S3_BUCKET_NAME": "your-s3-bucket-name",
        "SOCIAL_AUTH_TRAILING_SLASH": True,
        "OPENAI_API_KEY": "your-openai-api-key",
        "GRAFANA_CLOUD_OTLP_ENDPOINT": "",
        "GRAFANA_CLOUD_INSTANCE_ID": "",
        "GRAFANA_CLOUD_API_KEY": "",
    }
else:
    secret = json.loads(get_aws_secret_manager_secret(ENV))

GEMINI_API_KEY = secret.get("GEMINI_API_KEY")
OPENAI_API_KEY = secret.get("OPENAI_API_KEY")
GRAFANA_CLOUD_OTLP_ENDPOINT = secret.get("GRAFANA_CLOUD_OTLP_ENDPOINT", "")
GRAFANA_CLOUD_INSTANCE_ID = secret.get("GRAFANA_CLOUD_INSTANCE_ID", "")
GRAFANA_CLOUD_API_KEY = secret.get("GRAFANA_CLOUD_API_KEY", "")
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


STATIC_URL = "static/"


STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"

STATICFILES_DIRS = [
    BASE_DIR / "api" / "static",
]

REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "wildfire_assessment.authentication.Auth0JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-$ts=wt!%wmah^0-1aub!)o9*b60nqwe!$d(2%g4c4df^@nzirb"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "social_django",
    "rest_framework",
    "django_extensions",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "wildfire_assessment",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "api.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "api", "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "social_django.context_processors.backends",
            ],
        },
    },
]

WSGI_APPLICATION = "api.wsgi.application"

SOCIAL_AUTH_TRAILING_SLASH = secret[
    "SOCIAL_AUTH_TRAILING_SLASH"
]  # Remove trailing slash from routes
SOCIAL_AUTH_AUTH0_DOMAIN = secret["SOCIAL_AUTH_AUTH0_DOMAIN"]
SOCIAL_AUTH_AUTH0_KEY = secret["SOCIAL_AUTH_AUTH0_KEY"]
SOCIAL_AUTH_AUTH0_SECRET = secret["SOCIAL_AUTH_AUTH0_SECRET"]
SOCIAL_AUTH_AUTH0_SCOPE = secret["SOCIAL_AUTH_AUTH0_SCOPE"].split(",")

AUTH0_AUDIENCE = secret.get("AUTH0_API_AUDIENCE")
AUTH0_DOMAIN = SOCIAL_AUTH_AUTH0_DOMAIN
AUTH0_ISSUER = f"https://{AUTH0_DOMAIN}/"
AUTH0_JWKS_URL = f"{AUTH0_ISSUER}.well-known/jwks.json"
AUTH0_EMAIL_CLAIM = secret.get("AUTH0_EMAIL_CLAIM")
AUTH0_HTTP_TIMEOUT = float(secret.get("AUTH0_HTTP_TIMEOUT"))
AUTH0_MANAGEMENT_CLIENT_ID = secret.get("AUTH0_MANAGEMENT_CLIENT_ID")
AUTH0_MANAGEMENT_CLIENT_SECRET = secret.get("AUTH0_MANAGEMENT_CLIENT_SECRET")
AUTH0_MANAGEMENT_AUDIENCE = f"https://{AUTH0_DOMAIN}/api/v2/"
AUTH0_MANAGEMENT_TOKEN_URL = f"https://{AUTH0_DOMAIN}/oauth/token"

S3_BUCKET_NAME = secret["S3_BUCKET_NAME"]

if not AUTH0_AUDIENCE:
    LOG.warning(
        "AUTH0_API_AUDIENCE is not configured. API requests that require Auth0 tokens will fail."
    )

ALLOWED_HOSTS = secret["DJANGO_ALLOWED_HOSTS"].split(",")
SECRET_KEY = secret["DJANGO_SECRET_KEY"]
DEBUG = secret["DJANGO_DEBUG"]
CSRF_TRUSTED_ORIGINS = secret["DJANGO_CSRF_TRUSTED_ORIGINS"].split(",")  # updated in Secrets Manager
DB_USERNAME = secret["DB_USERNAME"]
DB_PASSWORD = secret["DB_PASSWORD"]
DB_NAME = secret["DB_NAME"]
DB_HOST = secret["DB_HOST"]


# PostgreSQL
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": DB_NAME,
        "USER": DB_USERNAME,
        "PASSWORD": DB_PASSWORD,
        "HOST": DB_HOST,
        "PORT": "5432",
    }
}


LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/admin/"

AUTHENTICATION_BACKENDS = {
    "social_core.backends.auth0.Auth0OAuth2",
    "django.contrib.auth.backends.ModelBackend",
}
# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Celery configuration — Redis runs in the docker-compose service named "redis"
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://redis:6379/0")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", CELERY_BROKER_URL)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_IMPORTS = (
    "wildfire_assessment.svc.processor",
    "wildfire_assessment.svc.notification",
)
CELERY_BEAT_SCHEDULE = {
    "cleanup-old-read-notifications": {
        "task": "wildfire_assessment.svc.notification.cleanup_old_read_notifications",
        "schedule": crontab(hour=9, minute=0),  # 09:00 UTC = 06:00 BRT
    },
}

# Terms of Service — bump this date to force all users to re-accept.
TERMS_LAST_UPDATED = "2026-02-25"


if ENV in ["local", "dev"]:
    REST_FRAMEWORK["DEFAULT_SCHEMA_CLASS"] = "drf_spectacular.openapi.AutoSchema"
    INSTALLED_APPS += ["drf_spectacular"]

    SPECTACULAR_SETTINGS = {
        "TITLE": "Wildfire Assessment API V2",
        "DESCRIPTION": "Auto generated openApi 3.0 docs",
        "VERSION": "1.0.0",
        "SORT_OPERATION_PARAMETERS": False,
        "APPEND_COMPONENTS": {
            "securitySchemes": {
                "BearerAuth": {
                    "type": "http",
                    "scheme": "bearer",
                    "bearerFormat": "JWT",
                    "description": "JWT Authorization header using the Bearer scheme. Example: 'Authorization: Bearer <token>'",
                }
            }
        },
        "SECURITY": [{"BearerAuth": []}],
    }

    # DJANGO CORS HEADERS
    INSTALLED_APPS += ["corsheaders"]

    MIDDLEWARE.insert(2, "corsheaders.middleware.CorsMiddleware")
    CORS_ALLOW_CREDENTIALS = True
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOW_METHODS = [
        "DELETE",
        "GET",
        "OPTIONS",
        "PATCH",
        "POST",
        "PUT",
    ]

    CORS_ALLOW_HEADERS = [
        "accept",
        "accept-encoding",
        "authorization",
        "content-type",
        "dnt",
        "origin",
        "user-agent",
        "x-csrftoken",
        "x-requested-with",
    ]

    CORS_EXPOSE_HEADERS = [
        "x-ai-provider",
    ]

    os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true"  # only use in development
