import { useLanguage } from "../../context/LanguageContext";

const TERMS_DATE = "2026-02-24";

const content = {
  en: {
    intro:
      "Welcome to the Wildfire Damage Assessment Platform (\"Platform\"), operated by Brazil Flying Labs. By accessing or using this Platform, you agree to be bound by these Terms of Service. If you do not agree, you may not use the Platform.",
    sections: [
      {
        title: "1. Service Description",
        body: "The Platform provides wildfire damage assessment tools using satellite imagery and geospatial analysis. It enables authorized users to analyze burn severity, generate scientific deliverables, and access AI-powered analysis reports for areas of interest across authorized countries.",
      },
      {
        title: "2. Account and Access",
        items: [
          "Access to the Platform requires authentication via Auth0. You are responsible for maintaining the security of your account credentials.",
          "Account activation requires administrator approval. Access is granted on a per-country basis.",
          "You agree to use the Platform only for its intended purpose of wildfire damage assessment and related activities.",
          "Brazil Flying Labs reserves the right to suspend or terminate access at any time, with or without notice.",
        ],
      },
      {
        title: "3. Data Collection and Analytics",
        body: "To improve our services and understand how the Platform is used, we collect usage analytics. This includes:",
        items: [
          "Page views and navigation patterns within the Platform.",
          "Interactions with buttons, forms, and other interface elements (autocaptured via PostHog).",
          "Session metadata such as browser type, screen resolution, and general location.",
          "Performance metrics and error reports (via Grafana Faro) to ensure Platform reliability.",
        ],
        footer:
          "This data is used exclusively for Platform improvement, debugging, and usage analytics. It is not sold to third parties.",
      },
      {
        title: "4. Data Storage and Security",
        items: [
          "All data is stored on secure cloud infrastructure (Amazon Web Services) with encryption at rest and in transit.",
          "Geospatial data and analysis results are stored in association with your account for retrieval and historical reference.",
          "Analytics data is processed by PostHog (US cloud) and Grafana Cloud, both of which comply with industry-standard security practices.",
          "We implement reasonable security measures to protect your data, but no system is completely secure. You acknowledge this inherent limitation.",
        ],
      },
      {
        title: "5. Data Protection and Privacy (LGPD & GDPR)",
        body: "Brazil Flying Labs is committed to protecting your personal data in compliance with applicable data protection regulations, including the Brazilian General Data Protection Law (Lei Geral de Proteção de Dados — LGPD, Law No. 13,709/2018) and the European Union General Data Protection Regulation (GDPR). Under these regulations, you have the following rights:",
        items: [
          "Right of access: You may request information about what personal data we process about you.",
          "Right to rectification: You may request correction of inaccurate or incomplete personal data.",
          "Right to deletion: You may request the deletion of your personal data, subject to legal retention obligations.",
          "Right to data portability: You may request a copy of your data in a structured, machine-readable format.",
          "Right to withdraw consent: You may withdraw your consent to data processing at any time by contacting us.",
          "Right to object: You may object to the processing of your personal data for certain purposes.",
        ],
        footer:
          "The legal basis for processing your data includes the performance of this agreement, your consent, and our legitimate interest in improving the Platform. To exercise any of these rights, please contact Brazil Flying Labs at the email address provided by your administrator.",
      },
      {
        title: "6. Open Source and Licensing",
        items: [
          "The Platform is open-source software released under the MIT License. Brazil Flying Labs does not claim proprietary ownership of the Platform's source code.",
          "The Platform is provided free of charge on an \"as is\" basis. Brazil Flying Labs reserves the right to modify, suspend, or discontinue the Platform or any part of its services at its sole discretion, with or without notice.",
          "Satellite imagery is sourced from public datasets (e.g., Sentinel-2 via Google Earth Engine) and is subject to their respective licenses.",
          "Analysis results generated by the Platform may be used by authorized users for their intended professional purposes.",
        ],
      },
      {
        title: "7. Limitation of Liability",
        body: "The Platform is provided \"as is\" and free of charge, without warranties of any kind, express or implied. Brazil Flying Labs shall not be liable for any direct, indirect, incidental, or consequential damages arising from your use of the Platform. Analysis results are provided for informational purposes and should be validated independently before making critical decisions.",
      },
      {
        title: "8. User Responsibilities",
        items: [
          "You agree not to misuse the Platform, including attempting to gain unauthorized access, interfering with its operation, or using it for unlawful purposes.",
          "You are responsible for the accuracy of the areas of interest and date ranges you submit for analysis.",
          "You agree not to share your account credentials or allow unauthorized individuals to access the Platform through your account.",
        ],
      },
      {
        title: "9. Changes to These Terms",
        body: "Brazil Flying Labs reserves the right to modify these Terms of Service at any time. Material changes will be communicated through the Platform. Continued use after changes constitutes acceptance of the updated terms. If you do not agree with the changes, you should stop using the Platform and contact an administrator.",
      },
      {
        title: "10. Contact",
        body: "For questions about these Terms of Service or to exercise your data rights, please contact Brazil Flying Labs at the email address provided by your administrator.",
      },
    ],
  },
  "pt-BR": {
    intro:
      "Bem-vindo(a) à Plataforma de Avaliação de Danos por Incêndios Florestais (\"Plataforma\"), operada pela Brazil Flying Labs. Ao acessar ou utilizar esta Plataforma, você concorda em cumprir estes Termos de Serviço. Se você não concordar, não poderá utilizar a Plataforma.",
    sections: [
      {
        title: "1. Descrição do Serviço",
        body: "A Plataforma fornece ferramentas de avaliação de danos por incêndios florestais utilizando imagens de satélite e análise geoespacial. Ela permite que usuários autorizados analisem a severidade de queimadas, gerem produtos científicos e acessem relatórios de análise por IA para áreas de interesse em países autorizados.",
      },
      {
        title: "2. Conta e Acesso",
        items: [
          "O acesso à Plataforma requer autenticação via Auth0. Você é responsável por manter a segurança das credenciais da sua conta.",
          "A ativação da conta requer aprovação do administrador. O acesso é concedido por país.",
          "Você concorda em utilizar a Plataforma apenas para seu propósito pretendido de avaliação de danos por incêndios florestais e atividades relacionadas.",
          "A Brazil Flying Labs reserva-se o direito de suspender ou encerrar o acesso a qualquer momento, com ou sem aviso prévio.",
        ],
      },
      {
        title: "3. Coleta de Dados e Análises",
        body: "Para melhorar nossos serviços e entender como a Plataforma é utilizada, coletamos análises de uso. Isso inclui:",
        items: [
          "Visualizações de páginas e padrões de navegação dentro da Plataforma.",
          "Interações com botões, formulários e outros elementos da interface (capturados automaticamente via PostHog).",
          "Metadados de sessão como tipo de navegador, resolução de tela e localização geral.",
          "Métricas de desempenho e relatórios de erros (via Grafana Faro) para garantir a confiabilidade da Plataforma.",
        ],
        footer:
          "Esses dados são usados exclusivamente para melhoria da Plataforma, depuração e análise de uso. Não são vendidos a terceiros.",
      },
      {
        title: "4. Armazenamento e Segurança de Dados",
        items: [
          "Todos os dados são armazenados em infraestrutura de nuvem segura (Amazon Web Services) com criptografia em repouso e em trânsito.",
          "Dados geoespaciais e resultados de análises são armazenados em associação com sua conta para consulta e referência histórica.",
          "Dados de análise são processados pelo PostHog (nuvem EUA) e Grafana Cloud, ambos em conformidade com práticas de segurança padrão do setor.",
          "Implementamos medidas de segurança razoáveis para proteger seus dados, mas nenhum sistema é completamente seguro. Você reconhece essa limitação inerente.",
        ],
      },
      {
        title: "5. Proteção de Dados e Privacidade (LGPD e GDPR)",
        body: "A Brazil Flying Labs está comprometida em proteger seus dados pessoais em conformidade com as regulamentações de proteção de dados aplicáveis, incluindo a Lei Geral de Proteção de Dados (LGPD — Lei nº 13.709/2018) e o Regulamento Geral de Proteção de Dados da União Europeia (GDPR). De acordo com essas regulamentações, você possui os seguintes direitos:",
        items: [
          "Direito de acesso: Você pode solicitar informações sobre quais dados pessoais processamos sobre você.",
          "Direito à retificação: Você pode solicitar a correção de dados pessoais imprecisos ou incompletos.",
          "Direito à eliminação: Você pode solicitar a exclusão dos seus dados pessoais, sujeito a obrigações legais de retenção.",
          "Direito à portabilidade dos dados: Você pode solicitar uma cópia dos seus dados em formato estruturado e legível por máquina.",
          "Direito à revogação do consentimento: Você pode revogar seu consentimento para o processamento de dados a qualquer momento entrando em contato conosco.",
          "Direito de oposição: Você pode se opor ao processamento dos seus dados pessoais para determinados fins.",
        ],
        footer:
          "A base legal para o processamento dos seus dados inclui a execução deste contrato, o seu consentimento e o nosso interesse legítimo em melhorar a Plataforma. Para exercer qualquer um desses direitos, entre em contato com a Brazil Flying Labs no endereço de e-mail fornecido pelo seu administrador.",
      },
      {
        title: "6. Código Aberto e Licenciamento",
        items: [
          "A Plataforma é um software de código aberto distribuído sob a Licença MIT. A Brazil Flying Labs não reivindica propriedade sobre o código-fonte da Plataforma.",
          "A Plataforma é fornecida gratuitamente, no estado em que se encontra (\"as is\"). A Brazil Flying Labs reserva-se o direito de modificar, suspender ou descontinuar a Plataforma ou qualquer parte de seus serviços a seu exclusivo critério, com ou sem aviso prévio.",
          "Imagens de satélite são provenientes de conjuntos de dados públicos (ex.: Sentinel-2 via Google Earth Engine) e estão sujeitas às suas respectivas licenças.",
          "Os resultados de análises gerados pela Plataforma podem ser utilizados por usuários autorizados para seus fins profissionais pretendidos.",
        ],
      },
      {
        title: "7. Limitação de Responsabilidade",
        body: "A Plataforma é fornecida \"como está\" e de forma gratuita, sem garantias de qualquer tipo, expressas ou implícitas. A Brazil Flying Labs não será responsável por quaisquer danos diretos, indiretos, incidentais ou consequenciais decorrentes do uso da Plataforma. Os resultados das análises são fornecidos para fins informativos e devem ser validados independentemente antes de tomar decisões críticas.",
      },
      {
        title: "8. Responsabilidades do Usuário",
        items: [
          "Você concorda em não fazer mau uso da Plataforma, incluindo tentar obter acesso não autorizado, interferir em sua operação ou usá-la para fins ilegais.",
          "Você é responsável pela precisão das áreas de interesse e intervalos de datas que submete para análise.",
          "Você concorda em não compartilhar suas credenciais de conta nem permitir que pessoas não autorizadas acessem a Plataforma através da sua conta.",
        ],
      },
      {
        title: "9. Alterações a Estes Termos",
        body: "A Brazil Flying Labs reserva-se o direito de modificar estes Termos de Serviço a qualquer momento. Alterações significativas serão comunicadas através da Plataforma. O uso contínuo após as alterações constitui aceitação dos termos atualizados. Se você não concordar com as alterações, deve parar de usar a Plataforma e entrar em contato com um administrador.",
      },
      {
        title: "10. Contato",
        body: "Para dúvidas sobre estes Termos de Serviço ou para exercer seus direitos sobre dados, entre em contato com a Brazil Flying Labs no endereço de e-mail fornecido pelo seu administrador.",
      },
    ],
  },
  fr: {
    intro:
      "Bienvenue sur la Plateforme d'Évaluation des Dommages par Incendies de Forêt (« Plateforme »), exploitée par Brazil Flying Labs. En accédant ou en utilisant cette Plateforme, vous acceptez d'être lié par ces Conditions d'Utilisation. Si vous n'acceptez pas, vous ne pouvez pas utiliser la Plateforme.",
    sections: [
      {
        title: "1. Description du Service",
        body: "La Plateforme fournit des outils d'évaluation des dommages par incendies de forêt utilisant l'imagerie satellite et l'analyse géospatiale. Elle permet aux utilisateurs autorisés d'analyser la gravité des brûlures, de générer des livrables scientifiques et d'accéder à des rapports d'analyse alimentés par l'IA pour des zones d'intérêt dans les pays autorisés.",
      },
      {
        title: "2. Compte et Accès",
        items: [
          "L'accès à la Plateforme nécessite une authentification via Auth0. Vous êtes responsable de la sécurité de vos identifiants de compte.",
          "L'activation du compte nécessite l'approbation de l'administrateur. L'accès est accordé par pays.",
          "Vous acceptez d'utiliser la Plateforme uniquement pour son objectif prévu d'évaluation des dommages par incendies de forêt et activités connexes.",
          "Brazil Flying Labs se réserve le droit de suspendre ou de résilier l'accès à tout moment, avec ou sans préavis.",
        ],
      },
      {
        title: "3. Collecte de Données et Analyses",
        body: "Pour améliorer nos services et comprendre comment la Plateforme est utilisée, nous collectons des analyses d'utilisation. Cela comprend :",
        items: [
          "Les pages consultées et les schémas de navigation au sein de la Plateforme.",
          "Les interactions avec les boutons, formulaires et autres éléments d'interface (capturés automatiquement via PostHog).",
          "Les métadonnées de session telles que le type de navigateur, la résolution d'écran et la localisation générale.",
          "Les métriques de performance et rapports d'erreurs (via Grafana Faro) pour assurer la fiabilité de la Plateforme.",
        ],
        footer:
          "Ces données sont utilisées exclusivement pour l'amélioration de la Plateforme, le débogage et l'analyse d'utilisation. Elles ne sont pas vendues à des tiers.",
      },
      {
        title: "4. Stockage et Sécurité des Données",
        items: [
          "Toutes les données sont stockées sur une infrastructure cloud sécurisée (Amazon Web Services) avec chiffrement au repos et en transit.",
          "Les données géospatiales et les résultats d'analyse sont stockés en association avec votre compte pour consultation et référence historique.",
          "Les données d'analyse sont traitées par PostHog (cloud US) et Grafana Cloud, qui respectent tous deux les pratiques de sécurité standard du secteur.",
          "Nous mettons en œuvre des mesures de sécurité raisonnables pour protéger vos données, mais aucun système n'est complètement sécurisé. Vous reconnaissez cette limitation inhérente.",
        ],
      },
      {
        title: "5. Protection des Données et Confidentialité (LGPD et RGPD)",
        body: "Brazil Flying Labs s'engage à protéger vos données personnelles conformément aux réglementations applicables en matière de protection des données, notamment la Loi Générale sur la Protection des Données du Brésil (Lei Geral de Proteção de Dados — LGPD, Loi nº 13.709/2018) et le Règlement Général sur la Protection des Données de l'Union Européenne (RGPD). En vertu de ces réglementations, vous disposez des droits suivants :",
        items: [
          "Droit d'accès : Vous pouvez demander des informations sur les données personnelles que nous traitons à votre sujet.",
          "Droit de rectification : Vous pouvez demander la correction de données personnelles inexactes ou incomplètes.",
          "Droit à l'effacement : Vous pouvez demander la suppression de vos données personnelles, sous réserve des obligations légales de conservation.",
          "Droit à la portabilité des données : Vous pouvez demander une copie de vos données dans un format structuré et lisible par machine.",
          "Droit de retrait du consentement : Vous pouvez retirer votre consentement au traitement des données à tout moment en nous contactant.",
          "Droit d'opposition : Vous pouvez vous opposer au traitement de vos données personnelles à certaines fins.",
        ],
        footer:
          "La base juridique du traitement de vos données comprend l'exécution de cet accord, votre consentement et notre intérêt légitime à améliorer la Plateforme. Pour exercer l'un de ces droits, veuillez contacter Brazil Flying Labs à l'adresse e-mail fournie par votre administrateur.",
      },
      {
        title: "6. Code Ouvert et Licence",
        items: [
          "La Plateforme est un logiciel open source distribué sous la Licence MIT. Brazil Flying Labs ne revendique aucune propriété sur le code source de la Plateforme.",
          "La Plateforme est fournie gratuitement, en l'état (« as is »). Brazil Flying Labs se réserve le droit de modifier, suspendre ou interrompre la Plateforme ou toute partie de ses services à sa seule discrétion, avec ou sans préavis.",
          "L'imagerie satellite provient de jeux de données publics (ex. : Sentinel-2 via Google Earth Engine) et est soumise à leurs licences respectives.",
          "Les résultats d'analyse générés par la Plateforme peuvent être utilisés par les utilisateurs autorisés à des fins professionnelles prévues.",
        ],
      },
      {
        title: "7. Limitation de Responsabilité",
        body: "La Plateforme est fournie « en l'état » et gratuitement, sans garantie d'aucune sorte, expresse ou implicite. Brazil Flying Labs ne sera pas responsable des dommages directs, indirects, accessoires ou consécutifs résultant de votre utilisation de la Plateforme. Les résultats d'analyse sont fournis à titre informatif et doivent être validés indépendamment avant de prendre des décisions critiques.",
      },
      {
        title: "8. Responsabilités de l'Utilisateur",
        items: [
          "Vous acceptez de ne pas faire un mauvais usage de la Plateforme, y compris tenter d'obtenir un accès non autorisé, interférer avec son fonctionnement ou l'utiliser à des fins illicites.",
          "Vous êtes responsable de l'exactitude des zones d'intérêt et des plages de dates que vous soumettez pour analyse.",
          "Vous acceptez de ne pas partager vos identifiants de compte ni permettre à des personnes non autorisées d'accéder à la Plateforme via votre compte.",
        ],
      },
      {
        title: "9. Modifications de ces Conditions",
        body: "Brazil Flying Labs se réserve le droit de modifier ces Conditions d'Utilisation à tout moment. Les modifications importantes seront communiquées via la Plateforme. L'utilisation continue après les modifications constitue l'acceptation des conditions mises à jour. Si vous n'acceptez pas les modifications, vous devez cesser d'utiliser la Plateforme et contacter un administrateur.",
      },
      {
        title: "10. Contact",
        body: "Pour toute question concernant ces Conditions d'Utilisation ou pour exercer vos droits sur les données, veuillez contacter Brazil Flying Labs à l'adresse e-mail fournie par votre administrateur.",
      },
    ],
  },
};

function TermsContent() {
  const { language } = useLanguage();
  const terms = content[language] || content.en;

  return (
    <div className="terms-text">
      <p className="terms-date">
        <small className="text-muted">
          {language === "pt-BR"
            ? `Última atualização: ${TERMS_DATE}`
            : language === "fr"
              ? `Dernière mise à jour : ${TERMS_DATE}`
              : `Last updated: ${TERMS_DATE}`}
        </small>
      </p>
      <p>{terms.intro}</p>
      {terms.sections.map((section, i) => (
        <div key={i} className="terms-section">
          <h3>{section.title}</h3>
          {section.body && <p>{section.body}</p>}
          {section.items && (
            <ul>
              {section.items.map((item, j) => (
                <li key={j}>{item}</li>
              ))}
            </ul>
          )}
          {section.footer && <p>{section.footer}</p>}
        </div>
      ))}
    </div>
  );
}

export default TermsContent;
