# Generated by Django 5.2.5 on 2025-09-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EcologicalReserve",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("polygon_path", models.CharField(max_length=255)),
            ],
        ),
    ]
