# Generated by Django 5.2.5 on 2025-10-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wildfire_assessment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ecologicalreserve",
            name="area_ha",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="ecologicalreserve",
            name="codigo_ibge",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name="ecologicalreserve",
            name="municipio",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ecologicalreserve",
            name="site",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
