# Generated by Django 5.2.5 on 2026-08-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildfire_assessment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprovider',
            name='model_name',
            field=models.CharField(default='gemini-2.0-flash-lite', help_text='Model identifier, e.g. gemini-2.0-flash-lite, gpt-4o-mini or deepseek-chat', max_length=100),
        ),
        migrations.AlterField(
            model_name='aiprovider',
            name='provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI'), ('deepseek', 'DeepSeek')], default='gemini', max_length=20),
        ),
    ]
