# Generated by Django 5.2.5 on 2025-11-11 16:12

import django.db.models.deletion
from django.db import migrations, models


def create_brazil_and_assign(apps, schema_editor):
    Country = apps.get_model("wildfire_assessment", "Country")
    EcologicalReserve = apps.get_model("wildfire_assessment", "EcologicalReserve")

    brazil, _ = Country.objects.get_or_create(name="Brazil", code="BR")
    EcologicalReserve.objects.filter(country__isnull=True).update(country=brazil)


class Migration(migrations.Migration):

    dependencies = [
        ("wildfire_assessment", "0002_ecologicalreserve_area_ha_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("code", models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="ecologicalreserve",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ecological_reserves",
                to="wildfire_assessment.country",
            ),
        ),
        migrations.RunPython(create_brazil_and_assign, migrations.RunPython.noop),
    ]
