# Generated by Django 5.2.5 on 2026-02-24 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildfire_assessment', '0023_aiprovider_singleton'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areaofinterest',
            options={'verbose_name': 'Area of Interest', 'verbose_name_plural': 'Areas of Interest'},
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='wildfire_as_user_id_88ff66_idx',
            old_name='wildfire_as_user_id_abcdef_idx',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aiprovider',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='areaofinterest',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areas_of_interest', to='wildfire_assessment.country'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
