# Generated by Django 5.2.5 on 2026-02-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wildfire_assessment", "0024_alter_areaofinterest_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisrun",
            name="scientific_dnbr_error",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="analysisrun",
            name="scientific_dndvi_error",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="analysisrun",
            name="scientific_rbr_error",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="analysisrun",
            name="scientific_rgb_post_fire_error",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="analysisrun",
            name="scientific_rgb_pre_fire_error",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
