# Generated by Django 5.2.5 on 2026-02-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wildfire_assessment", "0025_add_scientific_deliverable_error_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="expo_push_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
