# Generated by Django 5.2.5 on 2026-03-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildfire_assessment', '0029_alter_userprofile_default_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='roi_only',
            field=models.BooleanField(default=True),
        ),
    ]
