# Generated by Django 5.2.5 on 2026-03-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wildfire_assessment", "0030_analysisrun_roi_only"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisrun",
            name="cloud_threshold",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="analysisrun",
            name="days_before_after",
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name="analysisrun",
            name="post_fire_mosaic_strategy",
            field=models.CharField(
                default="best_available_per_tile_mosaic", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="analysisrun",
            name="pre_fire_mosaic_strategy",
            field=models.CharField(
                default="best_available_per_tile_mosaic", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="analysisrun",
            name="roi_only_bg_color",
            field=models.CharField(default="black", max_length=10),
        ),
    ]
