# Generated by Django 5.2.5 on 2026-03-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wildfire_assessment", "0031_analysisrun_cloud_threshold_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisrun",
            name="report_summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysisrun",
            name="report_summary_language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
