# Generated by Django 5.2.5 on 2026-03-25 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wildfire_assessment", "0032_analysisrun_report_summary_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisRunProvenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[("pre_fire", "Pre-fire"), ("post_fire", "Post-fire")],
                        max_length=10,
                    ),
                ),
                ("scene_id", models.CharField(max_length=255)),
                ("date", models.DateField()),
                (
                    "spacecraft_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("cloud_percent", models.FloatField(blank=True, null=True)),
                (
                    "analysis_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provenance_records",
                        to="wildfire_assessment.analysisrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Analysis Run Provenance",
                "verbose_name_plural": "Analysis Run Provenance Records",
                "ordering": ["phase", "date", "scene_id"],
            },
        ),
    ]
