# Generated by Django 5.2.5 on 2026-03-26 14:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildfire_assessment', '0033_analysisrunprovenance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrun',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='analysisrun',
            index=models.Index(fields=['status', 'completed_at'], name='analysisrun_status_completed'),
        ),
        migrations.AddIndex(
            model_name='areaofinterest',
            index=models.Index(fields=['name', 'country'], name='aoi_name_country'),
        ),
    ]
