# Generated by Django 5.2.5 on 2026-08-30 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildfire_assessment', '0034_add_database_indexes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='expo_push_token',
        ),
    ]
